services:
  front:
    build:
      context: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app:cached
      - /app/node_modules
    depends_on:
      - back

  back:
    build:
      context: ./back
    volumes:
      - ./back:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
